// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_sIKXf4C4K47KlNi01sf01IA25N40Cac',
    appId: '1:222926682196:web:e3ca092e9a72f7c62515c1',
    messagingSenderId: '222926682196',
    projectId: 'friend-of-the-farm',
    authDomain: 'friend-of-the-farm.firebaseapp.com',
    storageBucket: 'friend-of-the-farm.appspot.com',
    measurementId: 'G-82R32MYEDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqgkfvBe3NOWCjM9afIHJoFb9wq3Df_FM',
    appId: '1:222926682196:android:c4eb15d7896755922515c1',
    messagingSenderId: '222926682196',
    projectId: 'friend-of-the-farm',
    storageBucket: 'friend-of-the-farm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSS_cdR2Q0TndICpt1UlDZoDdiOQazgnc',
    appId: '1:222926682196:ios:379776d0877f11ab2515c1',
    messagingSenderId: '222926682196',
    projectId: 'friend-of-the-farm',
    storageBucket: 'friend-of-the-farm.appspot.com',
    iosClientId: '222926682196-9tb442svnvttrscalq0ohmlp3nvmoevj.apps.googleusercontent.com',
    iosBundleId: 'com.example.friendsOfTheFarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSS_cdR2Q0TndICpt1UlDZoDdiOQazgnc',
    appId: '1:222926682196:ios:379776d0877f11ab2515c1',
    messagingSenderId: '222926682196',
    projectId: 'friend-of-the-farm',
    storageBucket: 'friend-of-the-farm.appspot.com',
    iosClientId: '222926682196-9tb442svnvttrscalq0ohmlp3nvmoevj.apps.googleusercontent.com',
    iosBundleId: 'com.example.friendsOfTheFarm',
  );
}
